### ISSUE TITLE
GDAX weird data question

### ISSUE THREAD

**Issue by caherrerapa** [redcap3000/crypto-socket#6]
Thanks for sharing this. Pretty useful.

Not a bug actually, but any idea how come the GDAX data fluctuates so much if the latest price at the exchange doesn't move so abruptly? Delayed data sent to the socket maybe?
![crypto-socket_ _node_test_js_ _node_ _node_test_js_ _63x15_and_new_issue_ _redcap3000_crypto-socket](https://user-images.githubusercontent.com/1084920/34057047-6072ed1a-e1cd-11e7-9107-8a844a75af63.jpg)

**Comment by redcap3000** [comment]
I can't really answer this question based on any sort of foundation in 'reality' but.... I would assume that gdax hosts many trading bots. While you wont see the changes update in your web browser, the websocket is (apparently) reporting them. Otherwise possibly an issue with my _makeSocket function. Until more exchanges exhibit the same behavior i'm going to out on a limb and say thats not it. Or maybe it is and the way the library communicates with GDAX is off. I would not recommend asking GDAX/coinbase and expecting a response.) Did they update their documentation for websocket use lately? Probably not. Good luck.

**Comment by milonas115** [comment]
@caherrerapa The data isn't weird, the implementation is incorrect.
@redcap3000 , for accurate pricing from GDAX, you need to look at the price for any response that has type: 'match' ... You are looking at the price for every kind of order being placed which is why it's jumping thousands at a time sometimes (and blank for market orders).

**Comment by redcap3000** [comment]
Ok, I fixed it in the last commit, thanks, good catch.
