### ISSUE TITLE
Bittrex getticker response "null" case

### ISSUE THREAD

**Issue by RastoJ** [redcap3000/crypto-socket#7]
```
var responseObj = response.result
                          ^
TypeError: Cannot read property 'result' of null
```

Can be solved by something like 

`var responseObj = response ? response.result : null`

**Comment by redcap3000** [comment]
I agree. The entire library should take into account null/false AND undefined responses; but its not specifically an 'issue' with this repository rather than the state of the API being referenced. I will close this for now as it is too general to limit just to bittrex (which, btw, isn't actually a websocket, therefore should probably be removed or reimplemented to their provided websocket api.) I will be looking forward to any PR's that have appropriate API result response checking
